"""Create Address class

Revision ID: 028fcef304cb
Revises: caecda68db57
Create Date: 2023-07-10 11:11:43.793557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028fcef304cb'
down_revision = 'caecda68db57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('apartment_number', sa.String(), nullable=False),
    sa.Column('entrance', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('doorphone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('address')
    # ### end Alembic commands ###
