"""create Promotion class

Revision ID: 089976c33378
Revises: 0344281bdbc0
Create Date: 2023-07-07 11:18:50.426420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '089976c33378'
down_revision = '0344281bdbc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promotions')
    # ### end Alembic commands ###
