"""create ProductOrder class

Revision ID: 0baaea9a0e32
Revises: b1b2f4b16b64
Create Date: 2023-07-07 11:52:21.700857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0baaea9a0e32'
down_revision = 'b1b2f4b16b64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientProducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_ingredient', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productOrders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_order', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingredientsProduct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientsProduct',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ingredientsProduct_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_product', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_ingredient', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_ingredient'], ['ingredients.id'], name='ingredientsProduct_id_ingredient_fkey'),
    sa.ForeignKeyConstraint(['id_product'], ['products.id'], name='ingredientsProduct_id_product_fkey'),
    sa.PrimaryKeyConstraint('id', name='ingredientsProduct_pkey')
    )
    op.drop_table('productOrders')
    op.drop_table('ingredientProducts')
    # ### end Alembic commands ###
