"""create User class

Revision ID: 35d74371232d
Revises: 9406218a25dd
Create Date: 2023-07-07 11:08:39.322024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d74371232d'
down_revision = '9406218a25dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('middle_surname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bonus', sa.Integer(), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'photo_user')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photo_user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'bonus')
    op.drop_column('users', 'address')
    op.drop_column('users', 'email')
    op.drop_column('users', 'middle_surname')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
