"""create Order class

Revision ID: 49f427e3b1cc
Revises: 089976c33378
Create Date: 2023-07-07 11:27:06.246279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f427e3b1cc'
down_revision = '089976c33378'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id_chef', sa.Integer(), nullable=True),
    sa.Column('id_couriers', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('cost', sa.Double(), nullable=True),
    sa.ForeignKeyConstraint(['id_chef'], ['chefs.id'], ),
    sa.ForeignKeyConstraint(['id_couriers'], ['couriers.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
