"""Edit Order class

Revision ID: b0540639fe8f
Revises: 028fcef304cb
Create Date: 2023-07-10 13:17:11.686880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0540639fe8f'
down_revision = '028fcef304cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('orders', sa.Column('update_at', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'order_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'update_at')
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###
